sudo: required
language: java
services:
- docker
script:
- "./gradlew check shadowJar"
- docker build --pull -t navikt/postnummer-service:$COMMIT_SHORT .
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push navikt/postnummer-service:$COMMIT_SHORT
  fi
